# Generated by Django 3.1.4 on 2021-03-05 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toDoList', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['createdTime'], 'verbose_name_plural': 'EventTypes'},
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('description', models.TextField()),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('createdByUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('eventType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toDoList.eventtype')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'db_table': 'Event',
                'ordering': ['createdTime'],
            },
        ),
    ]
